// testimonialsData.js — Single source of truth for all testimonials
export const testimonials = [
  {
    id: 1,
    name: 'Dr. Peter Schütz',
    role: 'Vice Principal, Martin-Luther-Gymnasium, Eisenach, Germany',
    date: '2020-06-23',
    context: 'German Exchange Programme — Pingyang High School, 2018',
    initials: 'PS',
    color: '#4a90d9',
    excerpt: 'Jeremy was highly engaged and organized many events for the whole group. He showed great commitment, flexibly handled different roles, and proved to be a very gifted motivator with outstanding language competence.',
    full: 'I highly recommend Jeremy Thierry Chan as a student at your university. I met Jeremy during our exchange programme at Pingyang Zhong Xue. He was the host of one of our students. During this time, he was highly engaged and organized many events for the whole group. He felt highly responsible for the wellbeing of our group. It was impressive to see his interest in foreign culture and his ability to manage everything. During the time in Pingyang, Jeremy showed great commitment to the group\'s success. He flexibly handled different roles within his team and showed to be a very gifted motivator. Jeremy could fluently communicate in English and thus provided outstanding language competence. Based on his performance, I have no hesitations in recommending Jeremy.',
  },
  {
    id: 2,
    name: 'Dhiren Atodaria',
    role: 'Data Scientist / Engineer at Creditsafe, London',
    date: '2020-06-22',
    context: 'English Teacher — Pingyang High School, Zhejiang',
    initials: 'DA',
    color: '#27ae60',
    excerpt: 'One outstanding feature of Jeremy is his command of the English language. He is honest, dependable, and incredibly hard-working — an impressive speaker always able to communicate, no matter the situation.',
    full: 'It\'s my absolute pleasure to recommend Jeremy. One outstanding feature of Jeremy, certainly, is his command of the English language. He has a very high degree of nuanced understanding and is able to communicate at a high level in both daily and special situations. I have thoroughly enjoyed my time with Jeremy, and came to know him as a truly valuable asset to his teachers as well as the school. He is honest, dependable, and incredibly hard-working. Beyond that, he is an impressive speaker who is always able to communicate no matter the situation. His knowledge of English and expertise in intercultural communication was demonstrated every time we had a conversation. Along with his undeniable talent, Jeremy has always been an absolute joy to talk to. He is a great student, and always manages to foster positive discussions and bring the best out of other students and teachers.',
  },
  {
    id: 3,
    name: 'Ashlee Bishop',
    role: 'Program Coordinator, International Volunteer HQ (IVHQ), New Zealand',
    date: '2020-03-21',
    context: 'IVHQ Teaching Volunteer Programme — Ubud, Bali, July 2019',
    initials: 'AB',
    color: '#e67e22',
    excerpt: 'Jeremy went above what was asked of him as a volunteer. He showed great leadership, made meaningful connections with the children he taught, and successfully adjusted to total immersion in daily Indonesian life.',
    full: 'Jeremy made a great contribution to the program and went above what was asked of him as a volunteer. While working at a local school he taught English and showed great ability to use his English skills to teach English as a foreign language. He was also able to adapt his English accent to adapt to different situations. He also assisted with reading books to the children and executed his lesson plans that he took time to write out each day. The importance of Jeremy\'s contribution to the program can be seen in the enrichment of the children\'s lives through the individualized attention and care he provided them. In addition to the challenges Jeremy faced as a volunteer, he also succeeded in adjusting to the total immersion into daily Indonesian life, showed great leadership and made meaningful connections with the children he taught and his fellow volunteers.',
  },
  {
    id: 4,
    name: 'Green Lion Bali',
    role: 'Volunteer Programme Coordinator, Ubud, Bali, Indonesia',
    date: '2020-06-12',
    context: 'Green Lion Teaching Programme — Ubud, Bali, July 2019',
    initials: 'GL',
    color: '#16a085',
    excerpt: 'Mr. Jeremy Thierry Chan has been actively involved in the program and made a fine contribution to the project. With his excellent character and desire to succeed, he will make an excellent candidate for any organisation.',
    full: 'Mr. Jeremy Thierry Chan participated in our Teaching Program from 15.07.2019 for a week. His tasks and activities were in the local community at a local Primary School, teaching English during weekdays. During his stay, he has been actively involved in the program and made a fine contribution to the project. I believed that Mr. Jeremy Thierry Chan with his excellent character and his desire to succeed in this chosen project will make an excellent candidate. I strongly recommend him for your organisation. I wish him success in his academic and professional career.',
  },
  {
    id: 5,
    name: 'Simon Kaufmann',
    role: 'Fellow Volunteer, Zurich, Switzerland',
    date: '2019',
    context: 'Green Lion Volunteer Programme — Ubud, Bali, July 2019',
    initials: 'SK',
    color: '#8e44ad',
    excerpt: 'Jeremy was the only Chinese volunteer in the project. He got up at 6 AM every day to prepare his lessons — writing teaching materials in both Balinese and English by hand and practising his plan repeatedly before class.',
    full: 'I am Simon Kaufmann from Zurich, Switzerland. I met Jeremy in Ubud, Indonesia when we were volunteering with The Green Lion. He was the only Chinese in the project at that time. He taught English in a local school and did epic work. Nearly all the students in the school were in his class. His class started in the afternoon like the other volunteers, but he got up very early — around 6 AM — to prepare. There was neither a projector nor modern teaching equipment in the local school, so he wrote down everything he was going to teach in both Balinese and English on paper, made copies at the camp, and then practised his teaching plan again and again before class.',
  },
];
